package:
  name: reccdi
  version: 1.0

source:
  path: .

build:
  script_env:
    - LD_LIBRARY_PATH
  number: 0
  noarch: generic

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - cython

  run:
    - python
    - tifffile
    - pylibconfig2
    - xrayutilities
    - traits
    - mayavi


about:
  home: https://github.com/advancedPhotonSource/cdi
  license: BSD
  license_file: LICENSE
  summary: Implement and parallelize genetic algorithms and phase retrieval methods for Bragg CDI techniques.